---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: javawebapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: webappcontainer
          image: bikash1257/test:testing-v1
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: websvc
spec:
  type: LoadBalancer
  selector:
    app: javawebapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
